name: Release tag tracker

author: Benjamin Wuethrich

description: Update tags pointing to latest major and minor releases

branding:
  icon: tag
  color: blue

inputs:
  update-latest:
    description: Update a "latest" tag
    required: false
    default: false

  update-minor:
    description: Update vX.Y tags
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Run tag updater
      shell: bash
      run: |
        if [[ ${{ inputs.update-latest }} == 'true' ]]; then
            params+=('-l')
        fi

        if [[ ${{ inputs.update-minor }} == 'true' ]]; then
            params+=('-m')
        fi

        '${{ github.action_path }}/tagupdater' "${params[@]}"
