name: Release tag tracker

author: Benjamin Wuethrich

description: Update tags pointing to latest major and minor releases

branding:
  icon: tag
  color: blue

inputs:
  update-latest:
    type: boolean
    description: Update a "latest" tag
    required: false
    default: false

  update-minor:
    type: boolean
    description: Update vX.Y tags
    required: false
    default: true

  prepend-v:
    type: boolean
    description: Create tags in vX.Y.Z format
    required: false
    default: true

  pre-release-versions:
    type: string
    description: Create tags for pre-release versions. Input as array in order of specificity, e.g. "['beta', 'alpha']"
    required: false
    default: ""

runs:
  using: composite

  steps:
    - name: Run tag updater
      shell: bash
      env:
        latest: ${{ inputs.update-latest }}
        minor: ${{ inputs.update-minor }}
        prependv: ${{ inputs.prepend-v }}
        prereleaseversions: ${{ inputs.pre-release-versions }}
      run: |
        if [[ $latest == 'true' ]]; then
            params+=('-l')
        fi

        if [[ $minor == 'true' ]]; then
            params+=('-m')
        fi

        if [[ $prependv == 'false' ]]; then
            params+=('-v')
        fi

        params+=($prereleaseversions)

        "$GITHUB_ACTION_PATH/tagupdater" "${params[@]}"
