name: 'Update tracking branches'

on: push

jobs:
  release-tracking:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Check out code'
      uses: 'actions/checkout@v2'
    - name: 'Update branches tracking releases'
      uses: 'bewuethr/release-tracker-action@master'
